server {
    listen 8080;
    server_name _;

    # Inbound 1
    location = /vless {
        proxy_pass http://127.0.0.1:10001;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    # Inbound 2
    location = /ws2 {
        proxy_pass http://127.0.0.1:10002;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    # Inbound 3
    location = /ws3 {
        proxy_pass http://127.0.0.1:10003;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    # Inbound 4
    location = /ws4 {
        proxy_pass http://127.0.0.1:10004;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    # Inbound 5
    location = /ws5 {
        proxy_pass http://127.0.0.1:10005;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    # 3X-UI Panel
    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
